### ISSUE TITLE
Raspberry Pi GPIO Module

### ISSUE THREAD

**Issue by ckmiecik** [bitfocus/companion-module-raspberry-gpio#11]
I would love to be able to interact with the GPIO pins on my companion pi setup.  There is a module someone created but it seems like people (including myself) are not having luck getting it working as it might be outdated now?  It would be nice if there was an "official" module to support the GPIO pins in companion.  Here is the link to the project I am referring to.

https://github.com/bitfocus/companion-module-raspberry-gpio

Thank You

**Comment by isaacclausen** [comment]
I too would love for the GPIO module to be included in the official build.

**Comment by XENONChromatic** [comment]
Agreed this would be very helpful, overall GPIO support/integration. 

Please also see this request: https://github.com/bitfocus/companion-module-requests/issues/1245 

and there's also one for Numato. 

Some sort of general USB and/or Rpi + GPIO support would be incredibly useful

**Comment by jreynolds67** [comment]
Adding to this, would also love for GPIO support in the official build. Also having issues getting the old module working.

**Comment by Julusian** [comment]
This is fixed now that the module is included in the beta builds
