### ISSUE TITLE
Linking Raspi GPIO state to button 

### ISSUE THREAD

**Issue by RobJLocke** [bitfocus/companion-module-raspberry-gpio#14]
Pretty new to Companion but so far have managed to run CompanionPi headless on Pi4 4GB, install the GPIO module. I am hoping to link a simple contact closure to a Blackmagic videohub for camera preview. I have set up 4 momentary buttons from the BMD presets (work on test). Feedbacks (for specific pins) show contact closures (button colour change), but no actions are being forwarded to the BMD device itself. I'm guessing it is some kind of internal link but at I am at a loss to find the right method.

**Comment by istnv** [comment]
Feedback on a button is only able to change the appearance of the button (text/colors/graphics).
Add a trigger that watches that feedback event and add your desired BMD actions there.

**Comment by RobJLocke** [comment]
Got it. Companion needs a restart after setting new values in triggers. I was going around in circles until I realised this- nothing seemed to work.  Is this normal on CompanionPi?.Sent from Outlook for Android

**Comment by istnv** [comment]
Restart should not be necessary, but if it works :/
